# Use root/example as user/password credentials

services:

  todo-api-db:
    container_name: todo-api-db
    hostname: todo-api-db
    image: mariadb:10.11
    restart: unless-stopped
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-bigsecret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todo}
      MYSQL_USER: ${MYSQL_USER:-todo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}      
    volumes:
      - mysql:/var/lib/mysql
    # networks:
    #   - backend
    network_mode: host
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  todo-api:
    build: .
    env_file:
      - ./.env
    # working_dir: /go/src/app
    command: api
    container_name: todo-api
    hostname: todo-api
    # ports:
    #   - "${SERVER_PORT}:${SERVER_PORT}"
    # environment:
    #   - MYSQL_DSN='${MYSQL_DSN}'
    #   - SERVER_PORT=${SERVER_PORT:-3000}    
    depends_on:
      todo-api-db:
        condition: service_healthy
    # networks:
    #   - backend
    network_mode: host
  

volumes:
  mysql:
    driver: local
networks:
  backend: null