# Use root/example as user/password credentials

services:

  todo-api-db:
    container_name: todo-api-db
    hostname: todo-api-db
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-bigsecret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todo}
      MYSQL_USER: ${MYSQL_USER:-todo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}      
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql:
    driver: local
networks:
  backend: null