# Use root/example as user/password credentials

services:

  todo-api-db:
    container_name: todo-api-db
    hostname: todo-api-db
    image: mysql:9.3.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-bigsecret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todo}
      MYSQL_USER: ${MYSQL_USER:-todo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local